### PR TITLE
Oxedions/prometheus fix 1

### PR DESCRIPTION
**Pull request by oxedions**

### CODE REVIEW

**Review by strus38 — CHANGES_REQUESTED** [review]
Here are some feedbacks. Not only this PR changes but overall:

- README: what is data model 1.0.0, any link or spec?
- README: typo: 'To set k**e**rma username and password, use:'
- vars/main.yml should be bumped
- default/main.yml: prometheus_server_karma_password ... 
- templates/prometheus.yml.j2 ':9093' 'localhost:9090' are hardcoded
-  tasks/client.yml: tags: service should be added
- I think it is missing the instructions to set UI/API password somewhere in the doc (even a link to the official doc)

**Review by neilmunday — COMMENTED** [review]
Where is `prometheus_ipmi_scrape_equipment_profiles` defined? Is it worth adding an example in the README?

**Comment by oxedions** [comment]
Thanks a lot for reviewing the code !! 😊 

> * README: what is data model 1.0.0, any link or spec?

I added a link.

> * README: typo: 'To set k**e**rma username and password, use:'

Fixed

> * vars/main.yml should be bumped

Fixed

> * default/main.yml: prometheus_server_karma_password ...

What do you mean exactly ? I should not provide a default password ?

> * templates/prometheus.yml.j2 ':9093' 'localhost:9090' are hardcoded

I opened a feature request https://github.com/bluebanquise/community/issues/52

> * tasks/client.yml: tags: service should be added

Fixed

> * I think it is missing the instructions to set UI/API password somewhere in the doc (even a link to the official doc)

Same, opened a feature request https://github.com/bluebanquise/community/issues/52

**Comment by oxedions** [comment]
> Where is `prometheus_ipmi_scrape_equipment_profiles` defined? Is it worth adding an example in the README?

You mean, where the variables should be defined ? There is an example of the content of this variable in the readme, but indeed I did not defined where these variables should be defined.

**Comment by neilmunday** [comment]
> > Where is `prometheus_ipmi_scrape_equipment_profiles` defined? Is it worth adding an example in the README?
> 
> You mean, where the variables should be defined ? There is an example of the content of this variable in the readme, but indeed I did not defined where these variables should be defined.

Yeah, it wasn't immediately clear to me where `prometheus_ipmi_scrape_equipment_profiles` should be defined. I just wanted to check with you that the usage of this variable is documented somewhere.

**Comment by oxedions** [comment]
Ok got it. I will improve the readme then.

**Comment by oxedions** [comment]
I do not know if this is clear enough now. Basically, in this revision of the role, I tried to gather everything into a single file in the inventory.

**Review by neilmunday — APPROVED** [review]

**Comment by oxedions** [comment]
Thanks a lot guys for the review 😊

**Pull request merged**
