### PR TITLE
Oxedions/ubuntus

### PR DESCRIPTION
**Pull request by oxedions**
Integrate support for Ubuntu into slurm role

### CODE REVIEW

**Comment by strus38** [comment]
what is the status?

**Comment by oxedions** [comment]
Now ready 🙂

**Review by neilmunday — COMMENTED** [review]
Looks ok though I've not dabbled with cusom filter plugins before.

**Comment by oxedions** [comment]
@neilmunday no pb ! This filter is now used in many core roles as well. It is just more portable here, as I couldn't find a proper way for now to create a deb file for this filter...

**Pull request merged**
