### PR TITLE
Feat: haproxy - role creation

### PR DESCRIPTION
**Pull request by oxedions**
Configure a basic haproxy configuration for load balancing combined with high_availability role.

### CODE REVIEW

**Review by ginomcevoy — COMMENTED** [review]
Looks good to me so far.
My only question is where would we define the haproxy_nodes dictionary and haproxy_bind_ip variable; I guess it would go into group_vars/all/general_settings/haproxy.yml ? 
If that is a good choice, we should add that to the role. README.md

I will test this soon on a HA virtual cluster :)

**Review by ginomcevoy — COMMENTED** [review]
@oxedions ,
I am running this role on a HA virtual cluster, and set repository_ip = haproxy_bind_ip so that the repositories_client role uses the haproxy IP.

I am getting a very strange behavior when trying to access content via HTTP:

```
[root@management2 ~]# wget http://10.30.0.57/repositories//redhat/8/x86_64/os/AppStream/repodata/repomd.xml
--2021-08-15 02:57:40--  http://10.30.0.57/repositories//redhat/8/x86_64/os/AppStream/repodata/repomd.xml
Connecting to 10.30.0.57:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-08-15 02:57:40 ERROR 403: Forbidden.

[root@management2 ~]# wget http://10.30.0.57/repositories//redhat/8/x86_64/os/AppStream/repodata/repomd.xml
--2021-08-15 02:57:41--  http://10.30.0.57/repositories//redhat/8/x86_64/os/AppStream/repodata/repomd.xml
Connecting to 10.30.0.57:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4629 (4.5K) [text/xml]
Saving to: ‘repomd.xml’

repomd.xml                     100%[==================================================>]   4.52K  --.-KB/s    in 0s

2021-08-15 02:57:41 (228 MB/s) - ‘repomd.xml’ saved [4629/4629]
```

The first call fails with error 403, the second call succeeds. This goes back and forth (403, OK, 403, OK, ...). I am not able to list/install packages with dnf this way. I checked the httpd logs, and all the GET requests return with code 200 OK.

**Comment by oxedions** [comment]
Dear @ginomcevoy 

Thanks for testing.
Are you sure file is accessible on both webservers ?
Since you have OK, 403, OK, 403, etc it seems to me that one of your two webservers is refusing serving the file. Did you check both web servers logs ?
Did you try to download the file using direct access on both servers ?

**Review by ginomcevoy — APPROVED** [review]
Oh, I completely forgot to look at the logs of the second server. I assumed that both my servers had the same configuration but the second management was missing a selinux policy to serve files via apache. Everything works now, thanks!

This is how I updated my HA setup from apache to haproxy:

1. Remove the vip+service pcs resources for httpd
2. Add the vip+service pcs resources for haproxy
3. Make sure pcs is happy (I struggled a bit with resource ordering)
4. Start httpd on both managements:
```
ansible-playbook playbooks/managements-ha.yml --tags repositories_server -e '{"enable_services":true, "start_services":true}'
```
5. Adjust the value of `services_ip.repository_ip` to match `haproxy_bind_ip`
6. Make sure that the nodes access the package repositories via haproxy:
```
ansible-playbook playbooks/managements-ha.yml --tags repositories_client
ansible-playbook playbooks/computes.yml --tags repositories_client
```

Maybe it is useful to mention all or some of these steps (4-6) in the README of haproxy as an example. But I approve this role as it is now.

**Comment by oxedions** [comment]
Thanks a lot for checking 😊 

Yes, readme should be improved I agree, it lacks integration to the high_availability role.
Also, I need to find a good way to sync systems if using haproxy, since repositories should be available on all systems, but also diskless images, ipxe stuff, etc. I am afraid nfs like proposed in high_availability readme will not handle the load.

Was considering https://github.com/syncthing/syncthing

**Comment by oxedions** [comment]
@ginomcevoy  I updated the readme.
I also enabled and started httpd service in the task, which makes sense I think.

So now it should be more compliant.

What is tricky is, http stuff is used at multiple positions in the stack, not only repositories.

**Pull request merged**
