### PR TITLE
Fix: ofed - Replace packages list by a group

### PR DESCRIPTION
**Pull request by oxedions**
Replace packages list by a simple group.

Easier to maintain.

### CODE REVIEW

**Review by btravouillon — CHANGES_REQUESTED** [review]
The dnf module does not work on CentOS 7.

**Comment by oxedions** [comment]
You are right. I will create subtasks.

**Comment by btravouillon** [comment]
[package module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html) should work: `This module actually calls the pertinent package modules for each system (apt, yum, etc).`
Is there an issue with groups?

**Comment by oxedions** [comment]
> 
> 
> [package module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html) should work: `This module actually calls the pertinent package modules for each system (apt, yum, etc).`
> Is there an issue with groups?

I will try and let you know 🙂

**Comment by strus38** [comment]
Where is this magic group defined "@Infiniband Support".
And since I am a newbie, is that valid on every linux distro since it is not defined somewhere in your changes?

**Comment by oxedions** [comment]
> 
> 
> Where is this magic group defined "@infiniband Support".
> And since I am a newbie, is that valid on every linux distro since it is not defined somewhere in your changes?

It is available in RHEL distributions only for what I know. However, keep in mind this will install OFED and not MOFED. So it is perfect for small clusters, or clusters who are using no more supported Mellanox cards. Or if you do not really care about absolute performances on the interconnect 😊

**Comment by oxedions** [comment]
Very late. Confirmed package works with groups 😊

**Review by btravouillon — APPROVED** [review]
Looks good to me. 👍

**Comment by oxedions** [comment]
Thanks a lot ! 😊

**Pull request merged**
