### PR TITLE
Correct karma package to install

### PR DESCRIPTION
**Pull request by Manu44410**
Correct karma package to install in vars/RedHat.yml

### CODE REVIEW

**Review by strus38 — CHANGES_REQUESTED** [review]
Any change must bump the version of the role and the update of it's version in the vars directory of the role

**Comment by Manu44410** [comment]
sorry, this is my first correction on a github project.
version is update

**Comment by oxedions** [comment]
Dear @Manu44410 

Thanks a lot for this PR. 😊  This is indeed a bug (I made it, apologies).

The BlueBanquise project is currently in the process of migrating to Ansible Collections. This repository was injected into main BlueBanquise repository recently (https://github.com/bluebanquise/bluebanquise/tree/dev/2.0/collections/monitoring/roles/prometheus). I kept community repository historic, so that contributions are not lost in the process. Community repository is now frozen.

If I merge your fix right now into this repository, I will have to duplicate the fix into BlueBanquise repository, but your contribution will be lost in the process (I am not sure I can cherry-pick a fix between 2 repository with different files path).
Would you accept to reopen this fix into the main BlueBanquise repository ? If yes, please branch from dev/2.0 branch, role is in the monitoring collection (https://github.com/bluebanquise/bluebanquise/blob/dev/2.0/collections/monitoring) then as you did here, update fix and role version, but also add your name in the monitoring collection galaxy.yml as contributor (https://github.com/bluebanquise/bluebanquise/blob/dev/2.0/collections/monitoring/galaxy.yml).

If you prefer I merge it here, I can, but I like to keep contributions in the history so if you can reopen in the main BlueBanquise repository, that would be nice: give Ceasar what belongs to Ceasar 😉

**Comment by Manu44410** [comment]
Hi @oxedions
No problem, I will reopen the fix in dev/2.0 branch

**Pull request closed without merging**
